plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'tpo.g16.blackwood'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId "tpo.g16.blackwood"
        minSdk 29
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    
    // Auth & Logging
    implementation 'com.auth0.android:jwtdecode:2.0.2'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'

    // Retrofit & Network
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // Glide para carga de imágenes
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'

    // WebSockets (STOMP) & RxJava
    implementation 'com.github.NaikSoftware:StompProtocolAndroid:1.6.6'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    // Splash screen
    implementation libs.core.splashscreen

    implementation libs.core.splashscreen
    implementation libs.retrofit
    implementation libs.retrofit.gson
    implementation libs.okhttp.logging
    implementation libs.gson
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    testImplementation libs.junit

    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}